
name: deploy SOM-Backend
on:
  push:
    branches:
      - feature/SOM-38
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v2

      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"
        id: install

      - name: configure aws #aws configure 팀 키값
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # 추가 해줘야함
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # 추가 해줘야함
          aws-region: ap-northeast-2

      - name: update cluster information
        run: aws eks update-kubeconfig --name 6team-cluster --region ap-northeast-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      ################ build and push #################

      - name: build and push docker image to ecr (admin)
        env:
          REGISTRY: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com # ECR주소
          REPOSITORY: team6-admin
          IMAGE_TAG: v8
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -f ./admin/Dockerfile ./admin
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: build and push docker image to ecr (board)
        env:
          REGISTRY: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com # ECR주소
          REPOSITORY: team6-board
          IMAGE_TAG: v8
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -f ./board/Dockerfile ./board
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: build and push docker image to ecr (batch)
        env:
          REGISTRY: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com # ECR주소
          REPOSITORY: team6-batch
          IMAGE_TAG: v8
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -f ./batch/Dockerfile ./batch
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

################ apply ################

      - name: eks kubectl admin apply
        run: |
          kubectl apply -f ./admin/k8s/som-admin-depl-serv.yml
          kubectl rollout restart deployment admin

      - name: eks kubectl board apply
        run: |
          kubectl apply -f ./board/k8s/som-board-depl-serv.yml
          kubectl rollout restart deployment board

      - name: eks kubectl batch apply
        run: |
          kubectl apply -f ./batch/k8s/som-batch-depl-serv.yml
          kubectl rollout restart deployment batch

